"""Add calculation explanation

Revision ID: 01359f9139e6
Revises: 71c59efeaa3c
Create Date: 2026-06-09 12:29:26.482526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01359f9139e6'
down_revision: Union[str, Sequence[str], None] = '71c59efeaa3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('calculation_explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'calculation_explanation')
    # ### end Alembic commands ###
